# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# coding: utf-8

    Lecture.create(:name => '半導体工学', :teacher => '名倉徹', :grade => '2', :term => '後期')
    Lecture.create(:name => '通信工学Ⅰ', :teacher => '太郎丸眞', :grade => '2', :term => '後期')
    Lecture.create(:name => '電子回路', :teacher => '末次正', :grade => '2', :term => '前期')
    Lecture.create(:name => '電気磁気学', :teacher => '名倉徹', :grade => '2', :term => '前期')
    Lecture.create(:name => '工業数学', :teacher => '鈴木孝将', :grade => '3', :term => '前期')
    Lecture.create(:name => '電子通信工学実験', :teacher => '太郎丸眞', :grade => '3', :term => '前期')
    Lecture.create(:name => 'ディジタル信号処理', :teacher => '大橋正良', :grade => '2', :term => '前期')
    Lecture.create(:name => 'ディジタル電子回路', :teacher => '佐藤寿倫', :grade => '2', :term => '後期')
    Lecture.create(:name => '工業英語', :teacher => '前田結花', :grade => '3', :term => '後期')
    Lecture.create(:name => '計算機工学Ⅰ', :teacher => '佐藤寿倫', :grade => '2', :term => '前期')
    Lecture.create(:name => '計算機工学Ⅱ', :teacher => '佐藤寿倫', :grade => '3', :term => '前期')
    Lecture.create(:name => '計算機工学Ⅲ', :teacher => '佐藤寿倫', :grade => '3', :term => '後期')
    Lecture.create(:name => '計算機ネットワーク', :teacher => '上山憲昭', :grade => '3', :term => '前期')
    Lecture.create(:name => 'マルチメディア概論', :teacher => '鶴田直之', :grade => '4', :term => '後期')
    Lecture.create(:name => 'プログラミング演習Ⅰ', :teacher => '鶴田直之', :grade => '2', :term => '前期')
    Lecture.create(:name => 'センサーと計測', :teacher => '鈴木孝将', :grade => '3', :term => '後期')
    Lecture.create(:name => '通信・放送システム', :teacher => '武藤浩二', :grade => '3', :term => '集中後期')
    Lecture.create(:name => '電気回路Ⅲ', :teacher => '末次正', :grade => '2', :term => '後期')
    Lecture.create(:name => 'オペレーティングシステム', :teacher => '小野晋太郎', :grade => '3', :term => '前期')
    Lecture.create(:name => 'マイクロコンピュータ', :teacher => 'モシニャガ・ワシリー', :grade => '3', :term => '前期')
    Lecture.create(:name => 'ネットワークシステム', :teacher => '中村遼', :grade => '3', :term => '後期')
    Lecture.create(:name => '情報系のための確率・統計', :teacher => '鶴田直之', :grade => '3', :term => '前期')
    Lecture.create(:name => '情報セキュリティ', :teacher => '上山憲昭', :grade => '3', :term => '後期')
    Lecture.create(:name => '通信法規', :teacher => '大橋正良', :grade => '3', :term => '前期')
    Lecture.create(:name => '情報職業論', :teacher => '廣重法道', :grade => '4', :term => '前期')
    Lecture.create(:name => '情報化社会論', :teacher => '廣重法道', :grade => '4', :term => '後期')
    Lecture.create(:name => '情報処理システム開発', :teacher => '中西恒夫', :grade => '3', :term => '前期')
    Lecture.create(:name => 'ロボティクス', :teacher => '小野晋太郎', :grade => '4', :term => '後期')
    Lecture.create(:name => '関数論', :teacher => '坂田繁洋', :grade => '2', :term => '後期')
    Lecture.create(:name => '微分積分Ⅲ', :teacher => '佐野友二', :grade => '2', :term => '前期')
    Lecture.create(:name => '微分積分Ⅳ', :teacher => '仙葉隆', :grade => '2', :term => '後期')
    Lecture.create(:name => '物理学D', :teacher => '山本大輔', :grade => '3', :term => '後期')
    Lecture.create(:name => '工業経営', :teacher => '森正紀', :grade => '4', :term => '前期')
    Lecture.create(:name => '数値計算法', :teacher => '文仙正俊', :grade => '2', :term => '前期')
    Lecture.create(:name => '半導体デバイス', :teacher => '名倉徹', :grade => '3', :term => '前期')
    Lecture.create(:name => '情報理論', :teacher => '大橋正良', :grade => '2', :term => '前期')
    Lecture.create(:name => '集積回路プロセス', :teacher => '鈴木孝将', :grade => '3', :term => '後期')
    Lecture.create(:name => '通信工学Ⅱ', :teacher => '大橋正良', :grade => '3', :term => '前期')
    Lecture.create(:name => '電子系のための情報処理', :teacher => '太郎丸眞', :grade => '3', :term => '後期')
    Lecture.create(:name => 'アナログ回路', :teacher => '末次正', :grade => '2', :term => '後期')
    Lecture.create(:name => '通信応用', :teacher => '太郎丸眞', :grade => '3', :term => '前期')
    Lecture.create(:name => '卒業論文', :teacher => '鈴木孝将', :grade => '4', :term => '集中通年')
    Lecture.create(:name => '電子物性', :teacher => '鈴木孝将', :grade => '2', :term => '前期')
    Lecture.create(:name => '光エレクトロニクス', :teacher => '文仙正俊', :grade => '3', :term => '前期')
    Lecture.create(:name => '制御工学', :teacher => '小野晋太郎', :grade => '2', :term => '後期')
    Lecture.create(:name => '電磁波理論', :teacher => '文仙正俊', :grade => '2', :term => '後期')
    Lecture.create(:name => 'オブジェクト指向プログラミング', :teacher => '中西恒夫', :grade => '3 ', :term => '前期')
    Lecture.create(:name => '音声情報処理工学', :teacher => '高橋伸弥', :grade => '3', :term => '後期')
    Lecture.create(:name => 'オートマトンと言語理論', :teacher => '鶴田直之', :grade => '2', :term => '後期')
    Lecture.create(:name => '化学実験', :teacher => '栗崎敏', :grade => '2', :term => '前期')
    Lecture.create(:name => '化学Ａ（自然界と物質の化学）', :teacher => '祢宜田啓史', :grade => '2', :term => '前期')
    Lecture.create(:name => '化学Ｂ（生活と環境の化学）', :teacher => '祢宜田啓史', :grade => '2', :term => '後期')
    Lecture.create(:name => '画像処理工学', :teacher => '鶴田直之', :grade => '3', :term => '前期')
    Lecture.create(:name => '基礎電気磁気学', :teacher => '名倉徹', :grade => '1', :term => '後期')
    Lecture.create(:name => '基礎防災学', :teacher => '重松幹二', :grade => '3', :term => '前期')
    Lecture.create(:name => '行列と行列式Ⅰ「TL-a」', :teacher => '仙葉隆', :grade => '1', :term => '前期')
    Lecture.create(:name => '行列と行列式Ⅰ「TL-b」', :teacher => '柳青', :grade => '1', :term => '前期')
    Lecture.create(:name => '行列と行列式Ⅱ「TL-a」', :teacher => '仙葉隆', :grade => '1', :term => '後期')
    Lecture.create(:name => '行列と行列式Ⅱ「TL-b」', :teacher => '宮内敏行', :grade => '1', :term => '後期')
    Lecture.create(:name => '研究開発序論', :teacher => '八尾滋', :grade => '3', :term => '前期')
    Lecture.create(:name => '建築防災', :teacher => '塚越雅幸', :grade => '4', :term => '前期')
    Lecture.create(:name => 'コンパイラ構成法', :teacher => '中西恒夫', :grade => '2', :term => '後期')
    Lecture.create(:name => '自然言語処理工学', :teacher => '吉村賢治', :grade => '3', :term => '後期')
    Lecture.create(:name => '情報工学実験Ａ', :teacher => 'モシニャガ，ワシリー', :grade => '3', :term => '前期')
    Lecture.create(:name => '情報工学実験Ｂ', :teacher => '鶴田直之', :grade => '3', :term => '前期')
    Lecture.create(:name => '情報数学', :teacher => '田辺利文', :grade => '2', :term => '前期')
    Lecture.create(:name => '数理統計Ⅰ', :teacher => '桑江一洋', :grade => '3', :term => '前期')
    Lecture.create(:name => '数理統計Ⅱ', :teacher => '桑江一洋', :grade => '3', :term => '後期')
    Lecture.create(:name => '図学Ⅰ', :teacher => '酒井幸仁', :grade => '1', :term => '前期')
    Lecture.create(:name => '総合工業論', :teacher => '柳瀬圭児', :grade => '3', :term => '後期')
    Lecture.create(:name => '卒業論文Ⅰ', :teacher => '鈴木孝将', :grade => '4', :term => '集中前期')
    Lecture.create(:name => '卒業論文Ⅱ', :teacher => '鈴木孝将', :grade => '4', :term => '集中後期')
    Lecture.create(:name => 'ターボ機械', :teacher => '稲毛真一', :grade => '4', :term => '後期')
    Lecture.create(:name => '知識工学', :teacher => '小野晋太郎', :grade => '3', :term => '前期')
    Lecture.create(:name => '電気回路Ⅰ', :teacher => '末次正', :grade => '1', :term => '前期')
    Lecture.create(:name => '電気回路Ⅱ', :teacher => '太郎丸眞', :grade => '1', :term => '後期')
    Lecture.create(:name => '電子情報基礎演習', :teacher => '鈴木孝将', :grade => '2', :term => '前期')
    Lecture.create(:name => '電子情報工学実験', :teacher => '末次正', :grade => '2', :term => '後期')
    Lecture.create(:name => '電子情報工学特別演習', :teacher => '鈴木孝将', :grade => '3', :term => '後期')
    Lecture.create(:name => '電子情報工学特論', :teacher => '鈴木孝将', :grade => '1', :term => '前期')
    Lecture.create(:name => 'データ構造とアルゴリズムⅠ', :teacher => '高橋伸弥', :grade => '2', :term => '前期')
    Lecture.create(:name => 'データ構造とアルゴリズムⅡ', :teacher => '高橋伸弥', :grade => '2', :term => '後期')
    Lecture.create(:name => 'データベースシステム「情報・情報システム」', :teacher => '高橋伸弥', :grade => '3', :term => '前期')
    Lecture.create(:name => '統計', :teacher => '仙葉隆', :grade => '2', :term => '後期')
    Lecture.create(:name => '都市計画', :teacher => '宮崎慎也', :grade => '3', :term => '前期')
    Lecture.create(:name => '微分積分Ⅰ「TL-b」', :teacher => '川崎英文', :grade => '1', :term => '前期')
    Lecture.create(:name => '微分積分Ⅰ「TL-a」', :teacher => '綿谷安男', :grade => '1', :term => '前期')
    Lecture.create(:name => '微分積分Ⅱ「TL-b」', :teacher => '川崎英文', :grade => '1', :term => '後期')
    Lecture.create(:name => '微分積分Ⅱ「TL-a」', :teacher => '綿谷安男', :grade => '1', :term => '後期')
    Lecture.create(:name => '物理学実験「TL-a」', :teacher => '端山和大', :grade => '1', :term => '前期')
    Lecture.create(:name => '物理学実験「TL-b」', :teacher => '平松信康', :grade => '1', :term => '後期')
    Lecture.create(:name => '物理学Ａ', :teacher => '武末尚久', :grade => '2', :term => '前期')
    Lecture.create(:name => 'プログラミングⅠ', :teacher => '吉村賢治', :grade => '1', :term => '前期')
    Lecture.create(:name => 'プログラミングⅡ', :teacher => '吉村賢治', :grade => '1', :term => '後期')
    Lecture.create(:name => 'プログラミング演習Ⅱ', :teacher => '中西恒夫', :grade => '2', :term => '後期')
    Lecture.create(:name => 'プロジェクト型ソフトウェア開発演習', :teacher => '中西恒夫', :grade => '3', :term => '後期')
    Lecture.create(:name => '力学Ａ「TL-b」', :teacher => '橋本正章', :grade => '1', :term => '前期')
    Lecture.create(:name => '力学Ａ「TL-a」', :teacher => '平松信康', :grade => '1', :term => '前期')
    Lecture.create(:name => '力学Ｂ「TL-b」', :teacher => '橋本正章', :grade => '1', :term => '後期')
    Lecture.create(:name => '力学Ｂ「TL-a」', :teacher => '眞砂卓史', :grade => '1', :term => '後期')
    Lecture.create(:name => '力学Ｃ', :teacher => '原一広', :grade => '2', :term => '前期')
    Lecture.create(:name => '流体工学Ⅰ', :teacher => '安東洋一', :grade => '3', :term => '前期')
    Lecture.create(:name => '流体工学Ⅱ', :teacher => '安東洋一', :grade => '3', :term => '後期')
    Lecture.create(:name => '論理回路', :teacher => 'モシニャガ，ワシリー', :grade => '2', :term => '前期')